LMSDEV-148
Aprende-com/moodle-block_aprende_coursenavigation pull request #1
Opened 2021-03-09 21:23 UTC by davidherzlos

2021-03-11 16:51 UTC, petermAprende requested changes
The change I care about is changing the admin setting to use admin_setting_configcheckbox. The CSS selector caught my attention, but I don't feel like I am knowledgeable enough to request any specific changes.

2021-03-11 16:51 UTC, petermAprende commented on block_course_modulenavigation.php
> +                        }
I found this confusing:
In PHP: 1 usually means true, so this reads to me as:
"If toggleshowrestricted is true, skip". It wasn't until I got to the settings page that I noticed that you had set No == 1. I would recommend changing to use a checkbox in the settings page to get a boolean value.

2021-03-11 16:51 UTC, petermAprende commented on scss/course_modulenavigation.scss
> +    .section {
Is this selector specific enough? I very much could be wrong, but I feel like we have run into issues in the past where our selectors were not specific enough and ended up selecting sections that we didn't intend.

2021-03-16 14:01 UTC, davidherzlos commented on scss/course_modulenavigation.scss
> +    .section {
Yes, it is specific, it is actually a descendant selector using the scss syntax.

2021-03-16 14:17 UTC, davidherzlos commented on block_course_modulenavigation.php
> +                        }
Ok, makes sense!

2021-03-16 14:17 UTC, davidherzlos commented on settings.php
> +    );
Ok, makes sense!

2021-03-26 17:51 UTC, merged